In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

In [4]:
df = pd.read_csv("E:\Guvi\MDTE\Mar 13\oral_cancer_prediction_dataset.csv")

In [5]:
df

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
0,1,Italy,36,Female,Yes,Yes,Yes,No,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,No,No
1,2,Japan,64,Male,Yes,Yes,Yes,No,Yes,Yes,...,No,No,1.782186,1,No Treatment,83.340103,77772.50,177,No,Yes
2,3,UK,37,Female,No,Yes,No,No,Yes,Yes,...,No,Yes,3.523895,2,Surgery,63.222871,101164.50,130,Yes,Yes
3,4,Sri Lanka,55,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
4,5,South Africa,68,Male,No,No,No,No,No,Yes,...,No,No,2.834789,3,No Treatment,44.293199,45354.75,52,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84917,84918,USA,46,Male,Yes,No,No,No,No,Yes,...,No,Yes,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
84918,84919,USA,41,Male,Yes,Yes,No,No,No,No,...,Yes,Yes,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
84919,84920,Taiwan,72,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,4.777394,1,Surgery,85.633426,81352.50,90,No,Yes
84920,84921,Japan,67,Male,Yes,No,No,No,No,No,...,Yes,No,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
84921,84922,Pakistan,75,Male,Yes,No,No,Yes,Yes,No,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,No,No

In [9]:
df["Treatment Type"].unique()

array(['No Treatment', 'Surgery', 'Radiation', 'Targeted Therapy',
       'Chemotherapy'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [10]:
cols = ["Gender","Country", "Tobacco Use", "Alcohol Consumption", "HPV Infection", "Betel Quid Use", "Chronic Sun Exposure",
        "Poor Oral Hygiene", "Diet (Fruits & Vegetables Intake)", "Family History of Cancer", "Compromised Immune System",
        "Oral Lesions", "Unexplained Bleeding", "Difficulty Swallowing", "White or Red Patches in Mouth","Early Diagnosis", "Oral Cancer (Diagnosis)", "Treatment Type"]

le = LabelEncoder()
for col in cols:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

In [11]:
df

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
0,1,6,36,0,1,1,1,0,0,1,...,0,0,0.000000,0,1,100.000000,0.00,0,0,0
1,2,7,64,1,1,1,1,0,1,1,...,0,0,1.782186,1,1,83.340103,77772.50,177,0,1
2,3,15,37,0,0,1,0,0,1,1,...,0,1,3.523895,2,3,63.222871,101164.50,130,1,1
3,4,13,55,1,1,1,0,1,0,1,...,0,0,0.000000,0,1,100.000000,0.00,0,1,0
4,5,12,68,1,0,0,0,0,0,1,...,0,0,2.834789,3,1,44.293199,45354.75,52,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84917,84918,16,46,1,1,0,0,0,0,1,...,0,1,0.000000,0,1,100.000000,0.00,0,1,0
84918,84919,16,41,1,1,1,0,0,0,0,...,1,1,0.000000,0,1,100.000000,0.00,0,1,0
84919,84920,14,72,1,1,1,0,1,0,1,...,0,0,4.777394,1,3,85.633426,81352.50,90,0,1
84920,84921,7,67,1,1,0,0,0,0,0,...,1,0,0.000000,0,1,100.000000,0.00,0,1,0
84921,84922,10,75,1,1,0,0,1,1,0,...,0,0,0.000000,0,1,100.000000,0.00,0,0,0

In [13]:
print(df["Survival Rate (5-Year, %)"].min(),df["Survival Rate (5-Year, %)"].max())

10.000750400475608 100.0

In [15]:
y = df["Survival Rate (5-Year, %)"]

In [14]:
x = df.drop(columns=["Survival Rate (5-Year, %)"],axis=1)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.25)

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [25]:
model1 = RandomForestRegressor().fit(x_train, y_train)
y_pred = model1.predict(x_test)
print(r2_score(y_test, y_pred),mean_squared_error(y_test, y_pred), mean_absolute_error(y_test,y_pred))

0.9842443262798621 10.932346091399733 1.9352779062191214

In [27]:
model2 = GradientBoostingRegressor().fit(x_train, y_train)
y_pred = model2.predict(x_test)
print(r2_score(y_test, y_pred),mean_squared_error(y_test, y_pred), mean_absolute_error(y_test,y_pred))

0.9846327054938061 10.662862471913838 1.9277970355442184

In [ ]:
model3 = AdaBoostRegressor().fit(x_train, y_train) #FINAL BETTER!
y_pred = model3.predict(x_test)
print(r2_score(y_test, y_pred),mean_squared_error(y_test, y_pred), mean_absolute_error(y_test,y_pred))

0.9846780842043609 10.631375670538175 1.9168727446952152

In [29]:
model4 = SVR().fit(x_train, y_train)
y_pred = model4.predict(x_test)
print(r2_score(y_test, y_pred),mean_squared_error(y_test, y_pred), mean_absolute_error(y_test,y_pred))

0.6715041511731763 227.93251324904537 8.390245168528851

In [30]:
model5 = XGBRegressor().fit(x_train, y_train)
y_pred = model5.predict(x_test)
print(r2_score(y_test, y_pred),mean_squared_error(y_test, y_pred), mean_absolute_error(y_test,y_pred))

0.9835843090317552 11.390310448288904 1.9757001960748224

In [31]:
import pickle

In [ ]:
pickle.dump(model3, open("5_Year_suvival_rate_prediction_model.pkl", "wb"))

In [ ]:
#Considering the closness of r2 score to 1 and lesser mean errors (absolute and squared), Model 3 stands as the best out of the 5 for now!

In [ ]:
#convert model into pickle file and download the same